name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  Linux:
    name: build-linux
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v1
     - name: Running cmake (Linux)
       run: |
         ls ${{github.workspace}}
         mkdir build
         cd build
         cmake ..
     - name: Build Solution (Linux)
       run: |
         cd build
         make
     - name: Testing (Linux)
       run: |
        cd build 
        ctest --output-on-failure


 
