name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  Linux:
    name: build-linux
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v1
     - uses: actions/setup-python@v4
       with:
         python-version: '3.10' 
     - name: Installing Jinja2
       run: python3 -m pip install Jinja2
     - name: Installing pytest
       run: python3 -m pip install pytest
     - name: Running cmake (Linux)
       run: |
         ls ${{github.workspace}}
         mkdir build
         cd build
         cmake -C Debug ..
     - name: Build Solution (Linux)
       run: |
         cd build
         make
     - name: Testing (Linux)
       run: |
        cd build 
        ctest -C Debug --output-on-failure
        
  
  Windows:
    name: build-windows
    runs-on: windows-latest
    steps:
     - uses: actions/checkout@v1
     - uses: actions/setup-python@v4
       with:
         python-version: '3.10' 
     - name: Installing Jinja2
       run: python.exe -m pip install Jinja2
     - name: Installing pytest
       run: python3 -m pip install pytest
     - name: Archive production artifacts
       uses: actions/upload-artifact@v3
       with:
           name: log-file
           path: |
            "D:/a/PENE2/PENE2/CMakeFiles/CMakeOutput.log"
     - name: Running cmake (Windows)
       run: |
         ls ${{github.workspace}}
         cmake -C Debug .
     - name: Build Solution (Windows)
       run: |
         cmake --build .
     - name: Testing (Windows)
       run: |
        ctest -C Debug --output-on-failure


 
